### PR TITLE
Prettified the XML in all 73 files

### PR DESCRIPTION
**Pull request by DavidHaslam**
Used **Notepad++** XML Tools plugin
- Linarize [sic]
- Pretty Print (XML only - with line breaks)
- File Save

As agreed in #23 &ndash; this is a large diff for every file.

NB. I will not make any further commits for this pull request, so that once this is merged, it will be easier to see subsequent differences.

### CODE REVIEW

**Comment by DavidHaslam** [comment]
I didn't bother to prettify the file `Bible_Vulgate_Glaire.xml` as this is already well structured.

**Comment by DavidHaslam** [comment]
@MarjorieBurghart 

Please review pull request - the big change was agreed in advance. :) 
Only XML layout is changed. Text content remains as before.

**Comment by DavidHaslam** [comment]
Gentle reminder.

**Comment by DavidHaslam** [comment]
You've gone very quiet. 

Is everything OK?

**Comment by MarjorieBurghart** [comment]
Sorry for going off the grid like that! I've been a bit busy with different things (work and personal). I need to refresh my memory about all this, reading the thread right now.

**Comment by MarjorieBurghart** [comment]
OK, done, that was pretty straightforward sorry!

**Comment by DavidHaslam** [comment]
Thanks for responding and for merging the PR.

No worries!  We all know how busy life and work can get at times.
And it's not as if I had no other projects to press on with.

Merry Christmas!

David

**Pull request merged**
